### ISSUE TITLE
A more descriptive name maybe

### ISSUE THREAD

**Issue by fakedrake** [infolab-csail/whoami-backup#1]
Arguably I am in a glass house when it comes to naming things but I noticed we have whoami and whoami-backup projects. One is an empty python project and this is a Java project (not empty). Being on the inside of infolab my best guess is that the python package is glue to make whoami-backup interact with WikipediaBase or wikithingsdb.

Maybe whoami and python-whoami (or whoampy to make the customary excruciating pun)?

**Comment by alvaromorales** [comment]
I'm afraid it's simpler than that! We're rewriting whoami in Python. Instead of starting a new repository, we decided to keep the commit history and just replace the Java files with an empty Python project.

whoami-backup is just a backup of the whoami repository before we made the switch to Python (in case we messed up the git history). When the Python rewrite progresses, we'll delete whoami-backup.
